services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pc_configurer'
      - 'POSTGRES_PASSWORD=Konteiner04'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
